name: Generate README

on:
    push:
        branches:
            - watch_list

permissions:
  contents: write
  pull-requests: write

jobs:
    load:
        runs-on: macOS
        steps:
          - uses: actions/checkout@v4

          - name: print
            run: |
              cat STOCKS | sort -o STOCKS
